# Generated by Django 5.1.7 on 2025-03-15 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ontology_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ontology_id', message="Ontology ID must be in the format 'CO_XXX' where XXX is a 3-digit number.", regex='^CO_\\d{3}$')], verbose_name='Ontology ID')),
                ('crop_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_crop_name', message='Crop name must only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')], verbose_name='Crop Name')),
            ],
            options={
                'verbose_name': 'Crop Master',
                'verbose_name_plural': 'Crops Master',
                'db_table': 'crop_master',
            },
        ),
    ]
