# Generated by Django 5.1.7 on 2025-03-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0002_climatedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatedata',
            name='temperature',
        ),
        migrations.AddField(
            model_name='climatedata',
            name='max_temperature_2m',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Max 2m Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='min_temperature_2m',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Min 2m Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='sea_surface_temperature',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Sea Surface Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='skin_temperature',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Skin Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='temperature_2m',
            field=models.FloatField(default=0.0, verbose_name='2m Temperature (°C)'),
        ),
    ]
