# Generated by Django 5.1.7 on 2025-03-24 06:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0003_remove_climatedata_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='climatedata',
            name='climate_dat_latitud_0b35a8_idx',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='longitude',
        ),
        migrations.AddField(
            model_name='climatedata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='climatedata',
            index=models.Index(fields=['location'], name='climate_dat_locatio_933f3d_idx'),
        ),
    ]
