# Generated by Django 5.2.1 on 2025-10-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0004_remove_climatedata_climate_dat_latitud_0b35a8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropmaster',
            name='agrovoc_notation',
            field=models.CharField(blank=True, help_text='AGROVOC local ID like c_12151', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cropmaster',
            name='agrovoc_uri',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='AGROVOC URI'),
        ),
    ]
