# Generated by Django 5.2.1 on 2025-10-10 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0006_simulationkey_simulationrun_simulationresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropmaster',
            name='agrovoc_notation',
        ),
        migrations.RemoveField(
            model_name='cropmaster',
            name='agrovoc_uri',
        ),
        migrations.AddField(
            model_name='cropmaster',
            name='notation',
            field=models.CharField(blank=True, help_text='skos:notation if present', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cropmaster',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent crop (from skos:broader)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='lumenix.cropmaster'),
        ),
        migrations.AddField(
            model_name='cropmaster',
            name='scheme',
            field=models.CharField(blank=True, help_text='ConceptScheme label (e.g., fruit, herb)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cropmaster',
            name='uri',
            field=models.URLField(blank=True, help_text='SKOS Concept URI from TTL', null=True, unique=True),
        ),
    ]
