# Generated by Django 5.2.1 on 2025-10-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0007_remove_cropmaster_agrovoc_notation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropmaster',
            name='ontology_id',
        ),
    ]
