# Generated by Django 5.2.1 on 2025-10-29 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0008_remove_cropmaster_ontology_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(help_text='Concept @id, e.g. https://.../vocab/concept/cereal/barley', unique=True)),
                ('pref_label', models.JSONField(blank=True, default=dict)),
                ('alt_label', models.JSONField(blank=True, default=dict)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('notation', models.JSONField(blank=True, default=dict)),
                ('broader', models.JSONField(blank=True, default=list)),
                ('narrower', models.JSONField(blank=True, default=list)),
                ('exact_match', models.JSONField(blank=True, default=list)),
                ('close_match', models.JSONField(blank=True, default=list)),
                ('related', models.JSONField(blank=True, default=list)),
                ('in_scheme', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vocabulary_concept',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(help_text='ConceptScheme @id, e.g. https://.../vocab/scheme/cereal', unique=True)),
                ('title', models.JSONField(blank=True, default=dict)),
                ('description', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'vocabulary_scheme',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.CharField(choices=[('plants', 'Plants'), ('pathogens', 'Pathogens')], max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vocabulary',
            },
        ),
        migrations.CreateModel(
            name='PathogenConcept',
            fields=[
            ],
            options={
                'verbose_name': 'Pathogen Concept',
                'verbose_name_plural': 'Pathogen Concepts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lumenix.concept',),
        ),
        migrations.CreateModel(
            name='PlantConcept',
            fields=[
            ],
            options={
                'verbose_name': 'Plant Concept',
                'verbose_name_plural': 'Plant Concepts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lumenix.concept',),
        ),
        migrations.CreateModel(
            name='ConceptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'created'), ('updated', 'updated')], max_length=16)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content_hash', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='lumenix.concept')),
            ],
            options={
                'db_table': 'vocabulary_concept_history',
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts', to='lumenix.scheme'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='lumenix.vocabulary'),
        ),
        migrations.AddField(
            model_name='concept',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='lumenix.vocabulary'),
        ),
        migrations.DeleteModel(
            name='CropMaster',
        ),
        migrations.AddIndex(
            model_name='concepthistory',
            index=models.Index(fields=['concept', 'changed_at'], name='vocabulary__concept_c84416_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['vocabulary'], name='vocabulary__vocabul_19282f_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['vocabulary'], name='vocabulary__vocabul_568fad_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['scheme'], name='vocabulary__scheme__ca74cc_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['content_hash'], name='vocabulary__content_15d008_idx'),
        ),
    ]
