# Generated by Django 5.2.1 on 2025-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0009_concept_scheme_vocabulary_pathogenconcept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='ambrosia_supported',
            field=models.BooleanField(default=False),
        ),
    ]
