# Generated by Django 5.2.1 on 2025-11-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0011_rolemaster_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoleMaster',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
