# Generated by Django 5.2.1 on 2025-12-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0012_remove_userprofile_role_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('identifier', models.SlugField(help_text="Stable key, e.g. 'climate_map', 'disease_risk_timeseries'.", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Name shown in admin, e.g. 'Climate Map (Europe)'.", max_length=200)),
                ('template_name', models.CharField(help_text="Django template to include for this chart, e.g. 'lumenix/charts/climate_map.html'.", max_length=255)),
                ('default_config', models.JSONField(blank=True, default=dict, help_text='Optional default config (layout, filters, options...) for this chart.')),
            ],
            options={
                'db_table': 'dashboard_charts',
            },
        ),
        migrations.CreateModel(
            name='DashboardViewMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.SlugField(help_text="Stable identifier, e.g. 'default', 'farmer', 'distributor', 'admin'.", unique=True)),
                ('label', models.CharField(help_text="Human-readable label, e.g. 'Farmer View'.", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description for this view/mode.')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this is the fallback mode when none is explicitly chosen.')),
            ],
            options={
                'db_table': 'dashboard_view_modes',
            },
        ),
        migrations.CreateModel(
            name='DashboardViewChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of charts within a mode.')),
                ('config_override', models.JSONField(blank=True, default=dict, help_text="Optional per-mode override of chart config (the 'how').")),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_modes', to='lumenix.dashboardchart')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_charts', to='lumenix.dashboardviewmode')),
            ],
            options={
                'db_table': 'dashboard_view_charts',
                'ordering': ['order'],
                'unique_together': {('mode', 'chart')},
            },
        ),
    ]
