# Generated by Django 5.2.1 on 2025-12-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0013_dashboardchart_dashboardviewmode_dashboardviewchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardchart',
            name='page_code',
            field=models.CharField(choices=[('landing', 'Dashboard landing page'), ('risk', 'Risk charts page')], default='landing', help_text='Which high-level page this chart belongs to.', max_length=20),
        ),
    ]
