# Generated by Django 5.2.1 on 2026-03-04 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0014_dashboardchart_page_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarChartLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('menu_code', models.CharField(choices=[('risk', 'Risk Charts')], default='risk', help_text='Sidebar menu group where this chart link appears.', max_length=20)),
                ('label_override', models.CharField(blank=True, help_text='Optional label shown in sidebar. If blank, chart label is used.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the sidebar menu.')),
                ('chart', models.ForeignKey(help_text='Chart target for this sidebar entry.', on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_links', to='lumenix.dashboardchart')),
            ],
            options={
                'verbose_name': 'Sidebar Chart',
                'verbose_name_plural': 'Sidebar Charts',
                'db_table': 'sidebar_chart_links',
                'ordering': ['menu_code', 'order', 'id'],
                'unique_together': {('menu_code', 'chart')},
            },
        ),
    ]
