# Generated by Django 5.2.1 on 2026-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0015_sidebarchartlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarchartlink',
            name='menu_icon',
            field=models.CharField(blank=True, default='grid', help_text="Feather icon name for this menu, e.g. 'grid', 'bar-chart-2'.", max_length=40),
        ),
        migrations.AddField(
            model_name='sidebarchartlink',
            name='menu_label',
            field=models.CharField(default='Charts', help_text="Top-level menu label shown in sidebar, e.g. 'Charts'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sidebarchartlink',
            name='label_override',
            field=models.CharField(blank=True, help_text='Optional submenu label. If blank, chart label is used.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sidebarchartlink',
            name='menu_code',
            field=models.SlugField(default='charts', help_text="Stable menu code, e.g. 'charts', 'exposure', 'alerts'."),
        ),
        migrations.AlterField(
            model_name='sidebarchartlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of submenu items within the same top-level menu.'),
        ),
    ]
