# Generated by Django 5.2.5 on 2026-03-05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lumenix", "0016_sidebarchartlink_menu_icon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutsRegion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "iri",
                    models.URLField(
                        help_text="NUTS IRI, e.g. http://data.europa.eu/nuts/code/NL42",
                        unique=True,
                    ),
                ),
                (
                    "notation",
                    models.CharField(
                        db_index=True,
                        help_text="NUTS code, e.g. NL42",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="NUTS level: 0, 1, 2, 3",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "pref_label",
                    models.CharField(
                        db_index=True,
                        help_text="Primary label from API",
                        max_length=255,
                    ),
                ),
                (
                    "alt_labels_en",
                    models.JSONField(blank=True, default=list, help_text="English alternative labels"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NUTS Region",
                "verbose_name_plural": "NUTS Regions",
                "db_table": "nuts_regions",
                "indexes": [
                    models.Index(fields=["level", "notation"], name="nuts_regions_level_9c12c9_idx"),
                    models.Index(fields=["level", "pref_label"], name="nuts_regions_level_9fa3d8_idx"),
                ],
                "unique_together": {("level", "notation")},
            },
        ),
    ]
