# Generated by Django 5.2.1 on 2026-03-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0017_nutsregion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'Concept', 'verbose_name_plural': 'Concepts'},
        ),
        migrations.AlterModelOptions(
            name='concepthistory',
            options={'verbose_name': 'Concept History', 'verbose_name_plural': 'Concept History'},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'verbose_name': 'Schema', 'verbose_name_plural': 'Schemas'},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name': 'Vocabulary', 'verbose_name_plural': 'Vocabularies'},
        ),
        migrations.RenameIndex(
            model_name='nutsregion',
            new_name='nuts_region_level_941c84_idx',
            old_name='nuts_regions_level_9c12c9_idx',
        ),
        migrations.RenameIndex(
            model_name='nutsregion',
            new_name='nuts_region_level_0bd5cf_idx',
            old_name='nuts_regions_level_9fa3d8_idx',
        ),
    ]
