# Generated by Django 5.2.1 on 2026-03-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0018_alter_concept_options_alter_concepthistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Model id from API payload', max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('source_url', models.TextField(help_text='Model download/source URL')),
                ('image_tag', models.CharField(blank=True, default='', max_length=512)),
                ('cpu_cores_required', models.FloatField(default=0.0)),
                ('ram_gb_required', models.FloatField(default=0.0)),
                ('gpu_count_required', models.PositiveIntegerField(default=0)),
                ('gpu_memory_gb_required', models.FloatField(default=0.0)),
                ('min_cuda_version_required', models.CharField(blank=True, max_length=64, null=True)),
                ('source_timestamp', models.BigIntegerField(blank=True, help_text='models[n]._id.timestamp', null=True)),
                ('source_date_ms', models.BigIntegerField(blank=True, help_text='models[n]._id.date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SCiO Model',
                'verbose_name_plural': 'SCiO Models',
                'db_table': 'scio_models',
                'indexes': [models.Index(fields=['name'], name='scio_models_name_bb2419_idx'), models.Index(fields=['updated_at'], name='scio_models_updated_733428_idx')],
            },
        ),
    ]
