# Generated by Django 5.2.1 on 2026-03-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0019_sciomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='nutsregion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutsregion',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='scheme',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='sciomodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sciomodel',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], db_index=True, default=1),
        ),
    ]
