# Generated by Django 6.0.5 on 2026-06-03 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0022_toxinqueryspec_toxinconcentrationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMenuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('menu_name', models.CharField(help_text="Public label shown in the sidebar, e.g. 'Dashboard', 'External Resources'.", max_length=100, verbose_name='Menu name')),
                ('menu_route', models.CharField(blank=True, default='', help_text="Django URL name (e.g. 'dashboard') or a full URL (https://...). Leave blank for Parent groups that only expand.", max_length=255, verbose_name='Menu route')),
                ('menu_icon', models.CharField(blank=True, default='', help_text="Feather icon name, e.g. 'home', 'activity', 'external-link'. Used for top-level Parent/Item nodes.", max_length=40, verbose_name='Menu icon')),
                ('menu_type', models.SmallIntegerField(choices=[(0, 'Parent (expandable group)'), (1, 'Clickable item (top-level link)'), (2, 'Submenu item (child of a parent)')], default=1, help_text='Parent = expandable group, Item = top-level clickable link, Submenu = child link nested under a Parent.', verbose_name='Menu type')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open the route in a new browser tab (useful for external links).', verbose_name='Open in new tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order within the same level (lower numbers show first).', verbose_name='Order')),
                ('parent', models.ForeignKey(blank=True, help_text='Required for Submenu items: the Parent (expandable) menu they belong to.', limit_choices_to={'menu_type': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lumenix.adminmenumaster', verbose_name='Parent menu')),
            ],
            options={
                'verbose_name': 'Admin Menu',
                'verbose_name_plural': 'Admin Menu Master',
                'db_table': 'admin_menu_master',
                'ordering': ['order', 'id'],
            },
        ),
    ]
