# Generated by Django 6.0.5 on 2026-06-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0023_adminmenumaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmenumaster',
            name='menu_route',
            field=models.CharField(blank=True, default='', help_text="Django URL name (e.g. 'dashboard'), an absolute path ('/risk-charts/...'), or a full URL (https://...). Leave blank for Parent groups that only expand.", max_length=2048, verbose_name='Menu route'),
        ),
    ]
