# Generated by Django 6.0.6 on 2026-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0025_rename_toxin_pipeline_to_pathogen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sciomodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterField(
            model_name='pathogenqueryspec',
            name='pathogen',
            field=models.SlugField(help_text="Source pathogen identifier, e.g. 'salmonella'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='pathogenqueryspec',
            name='plant',
            field=models.SlugField(help_text="Source plant identifier, e.g. 'lettuce'.", max_length=100),
        ),
    ]
