# Generated by Django 6.0.6 on 2026-06-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0029_chart_data_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathogenconcentrationrecord',
            name='provenance_payload',
        ),
        migrations.RemoveField(
            model_name='pathogenconcentrationrecord',
            name='request_payload',
        ),
    ]
