# Generated by Django 6.0.6 on 2026-06-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0030_remove_pathogenconcentrationrecord_provenance_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardviewchart',
            name='emphasis',
            field=models.CharField(choices=[('primary', 'Primary (prominent)'), ('secondary', 'Secondary (available, de-emphasised)'), ('disabled', 'Disabled (visible but greyed out)')], default='primary', help_text="How prominent this chart is in this view. 'Disabled' greys it out instead of hiding it.", max_length=12),
        ),
    ]
