# Generated by Django 6.1.1 on 2026-09-23 11:10

from django.db import migrations, models


def mark_charts_as_demo(apps, schema_editor):
    """The charts pages still hold illustrative data, so the menu says so."""
    apps.get_model("lumenix", "AdminMenuMaster").objects.filter(
        menu_name__iexact="Charts"
    ).update(note="demo")


def clear_charts_note(apps, schema_editor):
    apps.get_model("lumenix", "AdminMenuMaster").objects.filter(
        menu_name__iexact="Charts"
    ).update(note="")


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0044_pcr_region_observed_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmenumaster',
            name='note',
            field=models.CharField(blank=True, default='', help_text="Optional label shown next to the menu name, e.g. 'Demo'. Looks like a badge but leaves the item clickable.", max_length=40, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='adminmenumaster',
            name='badge',
            field=models.CharField(blank=True, default='', help_text="Optional small label shown next to the menu name, e.g. 'Future'. A badge also greys the item out and makes it unclickable.", max_length=20, verbose_name='Badge'),
        ),
        migrations.RunPython(mark_charts_as_demo, clear_charts_note),
    ]
