# Generated by Django 6.1.1 on 2026-10-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenix', '0045_menu_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathogenconcentrationrecord',
            name='growth_potential_auc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GrowthPotentialLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plant', models.SlugField(max_length=100)),
                ('pathogen', models.SlugField(help_text='Spelled as stored on the records/specs.', max_length=100)),
                ('model_id', models.CharField(blank=True, default='', max_length=256)),
                ('model_title', models.CharField(blank=True, default='', max_length=512)),
                ('y0', models.FloatField(help_text='Standardised initial model level, read from the curves.')),
                ('horizon_hours', models.FloatField(help_text='Length of the curve the source API returns.')),
                ('t_eval_hours', models.FloatField(default=48.0)),
                ('samples', models.JSONField(help_text='Sorted [temperature_c, auc] pairs at t_eval_hours.')),
                ('t_min', models.FloatField()),
                ('t_max', models.FloatField()),
                ('sample_count', models.IntegerField(default=0)),
                ('built_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Growth potential lookup',
                'verbose_name_plural': 'Growth potential lookups',
                'db_table': 'growth_potential_lookups',
                'constraints': [models.UniqueConstraint(fields=('plant', 'pathogen'), name='uq_growth_lookup_pair')],
            },
        ),
    ]
