services:
  ambrosia_postgres:
    image: postgres:latest
    container_name: ambrosia_pg_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER" ]
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ambrosia_pg_db_data:/var/lib/postgresql/data
    networks:
      - ambrosia_network

  ambrosia_pgadmin:
    image: dpage/pgadmin4
    container_name: ambrosia_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - ambrosia_postgres
    networks:
      - ambrosia_network

volumes:
  ambrosia_pg_db_data: {}

networks:
  ambrosia_network:
    external: true
