services:
  postgres:
    image: postgres:latest
    container_name: ambrosia_pg_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ambrosia_pg_db_data:/var/lib/postgresql/data
    networks:
      - ambrosia_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ambrosia_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ambrosia_network

volumes:
  ambrosia_pg_db_data: {}

networks:
  ambrosia_network:
    driver: bridge
